---
ansible_user: ansible
system_timezone: "UTC"
upgrade_packages: true

# Tell the k3s-ansible collection our group name
server_group: kubernetes
agent_group: agent

# Hetzner firewall handles this — don't let the collection touch it
manage_firewall: false
